// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bidi.proto

package BidirectionalCA;

public final class Bidi {
  private Bidi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReferenceLetterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReferenceLetterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReferenceLetterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReferenceLetterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBidi.proto\":\n\026ReferenceLetterRequest\022\016" +
      "\n\006course\030\001 \001(\t\022\020\n\010language\030\002 \001(\t\"/\n\027Refe" +
      "renceLetterResponse\022\024\n\014confirmation\030\001 \001(" +
      "\t2`\n\017ReferenceLetter\022M\n\022GetReferenceLett" +
      "er\022\027.ReferenceLetterRequest\032\030.ReferenceL" +
      "etterResponse\"\000(\0010\001B\023\n\017BidirectionalCAP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ReferenceLetterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReferenceLetterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReferenceLetterRequest_descriptor,
        new java.lang.String[] { "Course", "Language", });
    internal_static_ReferenceLetterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReferenceLetterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReferenceLetterResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
