// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bidi.proto

package BidirectionalCA;

public interface ReferenceLetterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReferenceLetterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * client request
   * </pre>
   *
   * <code>string course = 1;</code>
   */
  java.lang.String getCourse();
  /**
   * <pre>
   * client request
   * </pre>
   *
   * <code>string course = 1;</code>
   */
  com.google.protobuf.ByteString
      getCourseBytes();

  /**
   * <code>string language = 2;</code>
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 2;</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();
}
