// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bidi.proto

package BidirectionalCA;

public interface ReferenceLetterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReferenceLetterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * server response
   * </pre>
   *
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <pre>
   * server response
   * </pre>
   *
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
